/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : LEDBlue.h
**     Project     : ProcessorExpert
**     Processor   : MKL25Z128VLK4
**     Component   : LED
**     Version     : Component 01.062, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2014-05-27, 17:58, # CodeGen: 188
**     Abstract    :
**          This component implements a universal driver for a single LED.
**     Settings    :
**          Component name                                 : LEDBlue
**          Turned On with initialization                  : no
**          HW Interface                                   : 
**            On/Off                                       : Enabled
**              Pin                                        : LEDpin
**            PWM                                          : Disabled
**            High Value means ON                          : no
**          Shell                                          : Disabled
**     Contents    :
**         Init       - void LEDBlue_Init(void);
**         Deinit     - void LEDBlue_Deinit(void);
**         On         - void LEDBlue_On(void);
**         Off        - void LEDBlue_Off(void);
**         Neg        - void LEDBlue_Neg(void);
**         Get        - byte LEDBlue_Get(void);
**         Put        - void LEDBlue_Put(byte val);
**         SetRatio16 - void LEDBlue_SetRatio16(word ratio);
**
**     License   : Open Source (LGPL)
**     Copyright : Erich Styger, 2013, all rights reserved.
**     Web       : www.mcuoneclipse.com
**     This an open source software implementing a driver using Processor Expert.
**     This is a free software and is opened for education, research and commercial developments under license policy of following terms:
**     * This is a free software and there is NO WARRANTY.
**     * No restriction on use. You can use, modify and redistribute it for personal, non-profit or commercial product UNDER YOUR RESPONSIBILITY.
**     * Redistributions of source code must retain the above copyright notice.
** ###################################################################*/
/*!
** @file LEDBlue.h
** @version 01.00
** @brief
**          This component implements a universal driver for a single LED.
*/         
/*!
**  @addtogroup LEDBlue_module LEDBlue module documentation
**  @{
*/         

#ifndef __LEDBlue_H
#define __LEDBlue_H

/* MODULE LEDBlue. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */
#include "LEDpin2.h"

#include "Cpu.h"

#define LEDBlue_ClrVal()    LEDpin2_ClrVal() /* put the pin on low level */
#define LEDBlue_SetVal()    LEDpin2_SetVal() /* put the pin on high level */
#define LEDBlue_SetInput()  LEDpin2_SetInput() /* use the pin as input pin */
#define LEDBlue_SetOutput() LEDpin2_SetOutput() /* use the pin as output pin */

#define LEDBlue_PARSE_COMMAND_ENABLED  0 /* set to 1 if method ParseCommand() is present, 0 otherwise */


#define LEDBlue_On() LEDpin2_ClrVal()
/*
** ===================================================================
**     Method      :  LEDBlue_On (component LED)
**     Description :
**         This turns the LED on.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define LEDBlue_Off() LEDpin2_SetVal()
/*
** ===================================================================
**     Method      :  LEDBlue_Off (component LED)
**     Description :
**         This turns the LED off.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define LEDBlue_Neg() LEDpin2_NegVal()
/*
** ===================================================================
**     Method      :  LEDBlue_Neg (component LED)
**     Description :
**         This negates/toggles the LED
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define LEDBlue_Get() (!(LEDpin2_GetVal()))
/*
** ===================================================================
**     Method      :  LEDBlue_Get (component LED)
**     Description :
**         This returns logical 1 in case the LED is on, 0 otherwise.
**     Parameters  : None
**     Returns     :
**         ---             - Status of the LED (on or off)
** ===================================================================
*/

#define LEDBlue_Init() LEDBlue_Off()
/*
** ===================================================================
**     Method      :  LEDBlue_Init (component LED)
**     Description :
**         Performs the LED driver initialization.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define LEDBlue_Put(val)  ((val) ? LEDBlue_On() : LEDBlue_Off())
/*
** ===================================================================
**     Method      :  LEDBlue_Put (component LED)
**     Description :
**         Turns the LED on or off.
**     Parameters  :
**         NAME            - DESCRIPTION
**         val             - value to define if the LED has to be on or
**                           off.
**     Returns     : Nothing
** ===================================================================
*/

void LEDBlue_Deinit(void);
/*
** ===================================================================
**     Method      :  LEDBlue_Deinit (component LED)
**     Description :
**         Deinitializes the driver
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void LEDBlue_SetRatio16(word ratio);
/*
** ===================================================================
**     Method      :  LEDBlue_SetRatio16 (component LED)
**     Description :
**         Method to specify the duty cycle. If using a PWM pin, this
**         means the duty cycle is set. For On/off pins, values smaller
**         0x7FFF means off, while values greater means on.
**     Parameters  :
**         NAME            - DESCRIPTION
**         ratio           - Ratio value, where 0 means 'off' and
**                           0xffff means 'on'
**     Returns     : Nothing
** ===================================================================
*/

/* END LEDBlue. */

#endif
/* ifndef __LEDBlue_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.08]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
