/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : LEDGreen.h
**     Project     : ProcessorExpert
**     Processor   : MKL25Z128VLK4
**     Component   : LED
**     Version     : Component 01.062, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2014-05-27, 17:58, # CodeGen: 188
**     Abstract    :
**          This component implements a universal driver for a single LED.
**     Settings    :
**          Component name                                 : LEDGreen
**          Turned On with initialization                  : no
**          HW Interface                                   : 
**            On/Off                                       : Enabled
**              Pin                                        : LEDpin
**            PWM                                          : Disabled
**            High Value means ON                          : no
**          Shell                                          : Disabled
**     Contents    :
**         Init       - void LEDGreen_Init(void);
**         Deinit     - void LEDGreen_Deinit(void);
**         On         - void LEDGreen_On(void);
**         Off        - void LEDGreen_Off(void);
**         Neg        - void LEDGreen_Neg(void);
**         Get        - byte LEDGreen_Get(void);
**         Put        - void LEDGreen_Put(byte val);
**         SetRatio16 - void LEDGreen_SetRatio16(word ratio);
**
**     License   : Open Source (LGPL)
**     Copyright : Erich Styger, 2013, all rights reserved.
**     Web       : www.mcuoneclipse.com
**     This an open source software implementing a driver using Processor Expert.
**     This is a free software and is opened for education, research and commercial developments under license policy of following terms:
**     * This is a free software and there is NO WARRANTY.
**     * No restriction on use. You can use, modify and redistribute it for personal, non-profit or commercial product UNDER YOUR RESPONSIBILITY.
**     * Redistributions of source code must retain the above copyright notice.
** ###################################################################*/
/*!
** @file LEDGreen.h
** @version 01.00
** @brief
**          This component implements a universal driver for a single LED.
*/         
/*!
**  @addtogroup LEDGreen_module LEDGreen module documentation
**  @{
*/         

#ifndef __LEDGreen_H
#define __LEDGreen_H

/* MODULE LEDGreen. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */
#include "LEDpin3.h"

#include "Cpu.h"

#define LEDGreen_ClrVal()    LEDpin3_ClrVal() /* put the pin on low level */
#define LEDGreen_SetVal()    LEDpin3_SetVal() /* put the pin on high level */
#define LEDGreen_SetInput()  LEDpin3_SetInput() /* use the pin as input pin */
#define LEDGreen_SetOutput() LEDpin3_SetOutput() /* use the pin as output pin */

#define LEDGreen_PARSE_COMMAND_ENABLED  0 /* set to 1 if method ParseCommand() is present, 0 otherwise */


#define LEDGreen_On() LEDpin3_ClrVal()
/*
** ===================================================================
**     Method      :  LEDGreen_On (component LED)
**     Description :
**         This turns the LED on.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define LEDGreen_Off() LEDpin3_SetVal()
/*
** ===================================================================
**     Method      :  LEDGreen_Off (component LED)
**     Description :
**         This turns the LED off.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define LEDGreen_Neg() LEDpin3_NegVal()
/*
** ===================================================================
**     Method      :  LEDGreen_Neg (component LED)
**     Description :
**         This negates/toggles the LED
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define LEDGreen_Get() (!(LEDpin3_GetVal()))
/*
** ===================================================================
**     Method      :  LEDGreen_Get (component LED)
**     Description :
**         This returns logical 1 in case the LED is on, 0 otherwise.
**     Parameters  : None
**     Returns     :
**         ---             - Status of the LED (on or off)
** ===================================================================
*/

#define LEDGreen_Init() LEDGreen_Off()
/*
** ===================================================================
**     Method      :  LEDGreen_Init (component LED)
**     Description :
**         Performs the LED driver initialization.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define LEDGreen_Put(val)  ((val) ? LEDGreen_On() : LEDGreen_Off())
/*
** ===================================================================
**     Method      :  LEDGreen_Put (component LED)
**     Description :
**         Turns the LED on or off.
**     Parameters  :
**         NAME            - DESCRIPTION
**         val             - value to define if the LED has to be on or
**                           off.
**     Returns     : Nothing
** ===================================================================
*/

void LEDGreen_Deinit(void);
/*
** ===================================================================
**     Method      :  LEDGreen_Deinit (component LED)
**     Description :
**         Deinitializes the driver
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void LEDGreen_SetRatio16(word ratio);
/*
** ===================================================================
**     Method      :  LEDGreen_SetRatio16 (component LED)
**     Description :
**         Method to specify the duty cycle. If using a PWM pin, this
**         means the duty cycle is set. For On/off pins, values smaller
**         0x7FFF means off, while values greater means on.
**     Parameters  :
**         NAME            - DESCRIPTION
**         ratio           - Ratio value, where 0 means 'off' and
**                           0xffff means 'on'
**     Returns     : Nothing
** ===================================================================
*/

/* END LEDGreen. */

#endif
/* ifndef __LEDGreen_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.08]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
